#!/usr/bin/env bash
# Transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "Error: File transfer failed."
fi
