#!/bin/env bash
# Script that Configure Nginx so that its HTTP response contains a custom header

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root."
    exit 1
fi

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

sed -i '/server_name _;/a \\n\trewrite ^\/redirect_me https:\/\/github.com\/SPaci20 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

sed -i 's/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By "$HOSTNAME";/' /etc/nginx/nginx.conf

systemctl start nginx

echo "Nginx configured with custom header X-Served-By on $HOSTNAME"
