#!/bin/env bash
#Script that Configure Nginx so that its HTTP response contains a custom header 

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create Nginx configuration file
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By \$host;
    }
}
" | sudo tee /etc/nginx/sites-available/custom_header > /dev/null

# Create a symbolic link
sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

sudo service nginx restart
