#!/bin/env bash

# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal


cleanup() {
    echo "Cleaning up..."
    rm -f /var/run/myscript.pid
    exit 0
}

trap 'cleanup' SIGTERM SIGQUIT SIGINT

echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done
