#!/usr/bin/env bash
#Displays number from 1 to 100, In a list format
#Displays FizzBuzz when number is a multiple of 3 and 5
#Displays Fizz when number is multiple f 3
#Displays Buzz when number is multiple of 5

for ((i = 1; i <= 100; i++)); do
	if ((i % 3 == 0)) && ((i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
