#!/usr/bin/env bash
# Displays the content of current directory in format 
# Displays in a list format

for file in *; do
	if [[ "$file" != .* ]]; then
		name_after_dash="${file#*-}"
		echo "$name_after_dash"
	fi
done
